# Project information
site_name: 'RENTAL MANAGEMENT APP'
docs_dir: docs  # Where to find the English markdown files
site_dir: site  # Where to put the English HTML files
site_author: 'Hikmethan Kolay'
site_url: 'https://github.com/hikmethankolay/ce100-midterm-hikmethan-kolay-yagizemre-ozbilge-cpp'
site_description: >-
    RENTAL MANAGEMENT APP

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/coruhtech/6g-lock-model-cpp'
edit_uri: ''

# Copyright
copyright: Copyright &copy; 2019 - 2024 Hikmethan Kolay

theme:
  name: material
  
nav:
    - Introduction: 'index.md'
    - Architecture: 'architecture.md'
    - Security: 'security.md'
    - Developers: 'developers.md'
    - 'Windows Library Documentation': 'doxygenlibwin/html/index.html'
    - 'Windows Unit Test Documentation': 'doxygentestwin/html/index.html'
    - 'Windows Test Coverage': 'coveragereportlibwin/index.html'
    - 'Windows Libray Doc. Coverage': 'coverxygenlibwin/index.html'
    - 'Windows Unit Test Doc. Coverage': 'coverxygentestwin/index.html'
    - 'Windows Unit Test Results': 'testresultswin/index.html'
    - 'Linux Library Documentation': 'doxygenliblinux/html/index.html'
    - 'Linux Unit Test Documentation': 'doxygentestlinux/html/index.html'
    - 'Linux Test Coverage': 'coveragereportliblinux/index.html'
    - 'Linux Libray Doc. Coverage': 'coverxygenliblinux/index.html'
    - 'Linux Unit Test Doc. Coverage': 'coverxygentestlinux/index.html'
    - 'Linux Unit Test Results': 'testresultslinux/index.html'
